name: CI
on: [push, pull_request]

jobs:
  install:
    name: "Test install: (${{ matrix.python-version }}, ${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: pip install .
      - name: Test script
        run: fit-file-faker -h
